const gchar* iface = 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<interface>\n"
"  <requires lib=\"gtk+\" version=\"2.24\"/>\n"
"  <!-- interface-naming-policy project-wide -->\n"
"  <object class=\"GtkWindow\" id=\"mainwin\">\n"
"    <property name=\"can_focus\">False</property>\n"
"    <property name=\"title\" translatable=\"yes\">skrypt</property>\n"
"    <property name=\"resizable\">False</property>\n"
"    <property name=\"window_position\">center</property>\n"
"    <child>\n"
"      <object class=\"GtkVBox\" id=\"vbox1\">\n"
"        <property name=\"visible\">True</property>\n"
"        <property name=\"can_focus\">False</property>\n"
"        <property name=\"spacing\">5</property>\n"
"        <child>\n"
"          <object class=\"GtkFileChooserButton\" id=\"filechooser\">\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">False</property>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">5</property>\n"
"            <property name=\"position\">0</property>\n"
"          </packing>\n"
"        </child>\n"
"        <child>\n"
"          <object class=\"GtkHBox\" id=\"hbox1\">\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">False</property>\n"
"            <child>\n"
"              <object class=\"GtkLabel\" id=\"hsize_label\">\n"
"                <property name=\"width_request\">200</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">False</property>\n"
"                <property name=\"label\" translatable=\"yes\">Hash Size</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">False</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">0</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"hsize_b1\">\n"
"                <property name=\"label\" translatable=\"yes\">80	</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup1</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">1</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"hsize_b2\">\n"
"                <property name=\"label\" translatable=\"yes\">120</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup1</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">2</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"hsize_b3\">\n"
"                <property name=\"label\" translatable=\"yes\">160	</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup1</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">3</property>\n"
"              </packing>\n"
"            </child>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">3</property>\n"
"            <property name=\"position\">1</property>\n"
"          </packing>\n"
"        </child>\n"
"        <child>\n"
"          <object class=\"GtkHBox\" id=\"hbox2\">\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">False</property>\n"
"            <child>\n"
"              <object class=\"GtkLabel\" id=\"hrev_label\">\n"
"                <property name=\"width_request\">200</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">False</property>\n"
"                <property name=\"label\" translatable=\"yes\">Hash Revision	</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">False</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">0</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"hrev_b1\">\n"
"                <property name=\"label\" translatable=\"yes\">1</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup2</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">1</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"hrev_b2\">\n"
"                <property name=\"label\" translatable=\"yes\">2</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup2</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">2</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"hrev_b3\">\n"
"                <property name=\"label\" translatable=\"yes\">3</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup2</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">3</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"hrev_b4\">\n"
"                <property name=\"label\" translatable=\"yes\">4</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup2</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">4</property>\n"
"              </packing>\n"
"            </child>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">3</property>\n"
"            <property name=\"position\">2</property>\n"
"          </packing>\n"
"        </child>\n"
"        <child>\n"
"          <object class=\"GtkHBox\" id=\"hbox3\">\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">False</property>\n"
"            <child>\n"
"              <object class=\"GtkLabel\" id=\"kblock_label\">\n"
"                <property name=\"width_request\">200</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">False</property>\n"
"                <property name=\"label\" translatable=\"yes\">Key Block</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">False</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">0</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"kblock_b1\">\n"
"                <property name=\"label\" translatable=\"yes\">1</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup3</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">1</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"kblock_b2\">\n"
"                <property name=\"label\" translatable=\"yes\">2</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup3</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">2</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"kblock_b3\">\n"
"                <property name=\"label\" translatable=\"yes\">3</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup3</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">3</property>\n"
"              </packing>\n"
"            </child>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">3</property>\n"
"            <property name=\"position\">3</property>\n"
"          </packing>\n"
"        </child>\n"
"        <child>\n"
"          <object class=\"GtkHBox\" id=\"hbox4\">\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">False</property>\n"
"            <child>\n"
"              <object class=\"GtkLabel\" id=\"algo_label\">\n"
"                <property name=\"width_request\">200</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">False</property>\n"
"                <property name=\"label\" translatable=\"yes\">Algo</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">False</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">0</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"algo_b1\">\n"
"                <property name=\"label\" translatable=\"yes\">crc</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup4</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">1</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"algo_b2\">\n"
"                <property name=\"label\" translatable=\"yes\">sig</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup4</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">2</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkRadioButton\" id=\"algo_b3\">\n"
"                <property name=\"label\" translatable=\"yes\">deck</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"receives_default\">False</property>\n"
"                <property name=\"use_action_appearance\">False</property>\n"
"                <property name=\"active\">True</property>\n"
"                <property name=\"draw_indicator\">True</property>\n"
"                <property name=\"group\">radiogroup4</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">3</property>\n"
"              </packing>\n"
"            </child>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">3</property>\n"
"            <property name=\"position\">4</property>\n"
"          </packing>\n"
"        </child>\n"
"        <child>\n"
"          <object class=\"GtkHBox\" id=\"hbox5\">\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">False</property>\n"
"            <child>\n"
"              <object class=\"GtkLabel\" id=\"pcode_label\">\n"
"                <property name=\"width_request\">200</property>\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">False</property>\n"
"                <property name=\"label\" translatable=\"yes\">Pass Code</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">False</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"position\">0</property>\n"
"              </packing>\n"
"            </child>\n"
"            <child>\n"
"              <object class=\"GtkEntry\" id=\"pcode_entry\">\n"
"                <property name=\"visible\">True</property>\n"
"                <property name=\"can_focus\">True</property>\n"
"                <property name=\"invisible_char\">•</property>\n"
"                <property name=\"primary_icon_activatable\">False</property>\n"
"                <property name=\"secondary_icon_activatable\">False</property>\n"
"                <property name=\"primary_icon_sensitive\">True</property>\n"
"                <property name=\"secondary_icon_sensitive\">True</property>\n"
"              </object>\n"
"              <packing>\n"
"                <property name=\"expand\">True</property>\n"
"                <property name=\"fill\">True</property>\n"
"                <property name=\"padding\">7</property>\n"
"                <property name=\"position\">1</property>\n"
"              </packing>\n"
"            </child>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">3</property>\n"
"            <property name=\"position\">5</property>\n"
"          </packing>\n"
"        </child>\n"
"        <child>\n"
"          <object class=\"GtkButton\" id=\"go_b\">\n"
"            <property name=\"label\" translatable=\"yes\">GO</property>\n"
"            <property name=\"width_request\">600</property>\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">True</property>\n"
"            <property name=\"receives_default\">True</property>\n"
"            <property name=\"use_action_appearance\">False</property>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">3</property>\n"
"            <property name=\"position\">6</property>\n"
"          </packing>\n"
"        </child>\n"
"        <child>\n"
"          <object class=\"GtkProgressBar\" id=\"pbar\">\n"
"            <property name=\"visible\">True</property>\n"
"            <property name=\"can_focus\">False</property>\n"
"          </object>\n"
"          <packing>\n"
"            <property name=\"expand\">True</property>\n"
"            <property name=\"fill\">True</property>\n"
"            <property name=\"padding\">3</property>\n"
"            <property name=\"position\">7</property>\n"
"          </packing>\n"
"        </child>\n"
"      </object>\n"
"    </child>\n"
"  </object>\n"
"  <object class=\"GtkRadioButton\" id=\"radiogroup1\">\n"
"    <property name=\"label\" translatable=\"yes\">radiobutton</property>\n"
"    <property name=\"visible\">True</property>\n"
"    <property name=\"can_focus\">True</property>\n"
"    <property name=\"receives_default\">False</property>\n"
"    <property name=\"use_action_appearance\">False</property>\n"
"    <property name=\"active\">True</property>\n"
"    <property name=\"draw_indicator\">True</property>\n"
"  </object>\n"
"  <object class=\"GtkRadioButton\" id=\"radiogroup2\">\n"
"    <property name=\"label\" translatable=\"yes\">radiobutton</property>\n"
"    <property name=\"visible\">True</property>\n"
"    <property name=\"can_focus\">True</property>\n"
"    <property name=\"receives_default\">False</property>\n"
"    <property name=\"use_action_appearance\">False</property>\n"
"    <property name=\"active\">True</property>\n"
"    <property name=\"draw_indicator\">True</property>\n"
"  </object>\n"
"  <object class=\"GtkRadioButton\" id=\"radiogroup3\">\n"
"    <property name=\"label\" translatable=\"yes\">radiobutton</property>\n"
"    <property name=\"visible\">True</property>\n"
"    <property name=\"can_focus\">True</property>\n"
"    <property name=\"receives_default\">False</property>\n"
"    <property name=\"use_action_appearance\">False</property>\n"
"    <property name=\"active\">True</property>\n"
"    <property name=\"draw_indicator\">True</property>\n"
"  </object>\n"
"  <object class=\"GtkRadioButton\" id=\"radiogroup4\">\n"
"    <property name=\"label\" translatable=\"yes\">radiobutton</property>\n"
"    <property name=\"visible\">True</property>\n"
"    <property name=\"can_focus\">True</property>\n"
"    <property name=\"receives_default\">False</property>\n"
"    <property name=\"use_action_appearance\">False</property>\n"
"    <property name=\"active\">True</property>\n"
"    <property name=\"draw_indicator\">True</property>\n"
"  </object>\n"
"</interface>\n"
;
